### ISSUE TITLE
Got TypeError 

### ISSUE THREAD

**Issue by KhinChoWin-AI** [cjf8899/ReMix_Pytorch#1]
There is an imbalance between your GPUs. You may want to exclude GPU 4 which
    has less than 75% of the memory or cores of GPU 0. You can do so by setting
    the device_ids argument to DataParallel, or by setting the CUDA_VISIBLE_DEVICES
    environment variable.
  warnings.warn(imbalance_warn.format(device_ids[min_pos], device_ids[max_pos]))
Number of parameters of generator: 33892995
Number of parameters of mapping_network: 3259072
Number of parameters of style_encoder: 20949760
Number of parameters of discriminator: 20852803
Initializing generator...
Initializing mapping_network...
Initializing style_encoder...
Initializing discriminator...
Preparing DataLoader to fetch source images during the training phase...
Preparing DataLoader to fetch reference images during the training phase...
Preparing DataLoader for the generation phase...
Start training...
Traceback (most recent call last):
  File "main.py", line 190, in <module>
    main(args)
  File "main.py", line 59, in main
    solver.train(loaders)
  File "/home/revanth/vigil_kcw/ReMix_Pytorch/core/solver_remix.py", line 111, in train
    nets, args, x_real, y_org, y_trg, z_trg=z_trg, masks=masks)
  File "/home/revanth/vigil_kcw/ReMix_Pytorch/core/solver_remix.py", line 216, in compute_d_loss
    x_fake = nets.generator(x_real, s_trg, masks=masks)
  File "/home/revanth/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/revanth/.local/lib/python3.6/site-packages/torch/nn/parallel/data_parallel.py", line 168, in forward
    outputs = self.parallel_apply(replicas, inputs, kwargs)
  File "/home/revanth/.local/lib/python3.6/site-packages/torch/nn/parallel/data_parallel.py", line 178, in parallel_apply
    return parallel_apply(replicas, inputs, kwargs, self.device_ids[:len(replicas)])
  File "/home/revanth/.local/lib/python3.6/site-packages/torch/nn/parallel/parallel_apply.py", line 86, in parallel_apply
    output.reraise()
  File "/home/revanth/.local/lib/python3.6/site-packages/torch/_utils.py", line 434, in reraise
    raise exception
TypeError: Caught TypeError in replica 4 on device 4.
Original Traceback (most recent call last):
  File "/home/revanth/.local/lib/python3.6/site-packages/torch/nn/parallel/parallel_apply.py", line 61, in _worker
    output = module(*input, **kwargs)
  File "/home/revanth/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
TypeError: forward() missing 2 required positional arguments: 'x' and 's'

Any suggestions to solve?

**Comment by cjf8899** [comment]
hello.

I saw your error message and tried to figure out how to fix it.

The paper and I used 'StarGAN v2' as the baseline, and found the same error in the StarGAN v2 github issue.

https://github.com/clovaai/stargan-v2/issues/114
other repo issue : https://github.com/clovaai/deep-text-recognition-benchmark/issues/200

Hope this helps you.
