### ISSUE TITLE
How to solve forward() missing 2 required positional arguments: 'x' and 's'?

### ISSUE THREAD

**Issue by KhinChoWin-AI** [cjf8899/ReMix_Pytorch#4]
File "main.py", line 59, in main
    solver.train(loaders)
  File "/home1/ai20resch16001/ReMix_Pytorch/core/solver_remix.py", line 111, in train
    nets, args, x_real, y_org, y_trg, z_trg=z_trg, masks=masks)
  File "/home1/ai20resch16001/ReMix_Pytorch/core/solver_remix.py", line 222, in compute_d_loss
    x_fake = nets.generator(x_real, s_trg, masks=masks)
  File "/home1/ai20resch16001/anaconda3/envs/stargan-v2/lib/python3.6/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home1/ai20resch16001/anaconda3/envs/stargan-v2/lib/python3.6/site-packages/torch/nn/parallel/data_parallel.py", line 152, in forward
    outputs = self.parallel_apply(replicas, inputs, kwargs)
  File "/home1/ai20resch16001/anaconda3/envs/stargan-v2/lib/python3.6/site-packages/torch/nn/parallel/data_parallel.py", line 162, in parallel_apply
    return parallel_apply(replicas, inputs, kwargs, self.device_ids[:len(replicas)])
  File "/home1/ai20resch16001/anaconda3/envs/stargan-v2/lib/python3.6/site-packages/torch/nn/parallel/parallel_apply.py", line 85, in parallel_apply
    output.reraise()
  File "/home1/ai20resch16001/anaconda3/envs/stargan-v2/lib/python3.6/site-packages/torch/_utils.py", line 394, in reraise
    raise self.exc_type(msg)
TypeError: Caught TypeError in replica 2 on device 2.
Original Traceback (most recent call last):
  File "/home1/ai20resch16001/anaconda3/envs/stargan-v2/lib/python3.6/site-packages/torch/nn/parallel/parallel_apply.py", line 60, in _worker
    output = module(*input, **kwargs)
  File "/home1/ai20resch16001/anaconda3/envs/stargan-v2/lib/python3.6/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
TypeError: forward() missing 2 required positional arguments: 'x' and 's'

**Comment by KhinChoWin-AI** [comment]
It is because of Data Parallel in pytorch. Now, it is solved. I will closed now.
